# ---- TEST 
# Reference: https://playwright.dev/docs/docker
FROM mcr.microsoft.com/playwright:v1.22.0-focal

WORKDIR /app
COPY ./package.json /app/package.json
RUN npx playwright install --with-deps
COPY ./yarn.lock /app/yarn.lock
RUN yarn

COPY . /app
