version: "3.0"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
    ports:
      - '4000:4000'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - '4500:4500'
    environment:
      REACT_APP_SERVER_URL: 'https://jimanaka.com:4000'

      
