version: "3.6"
services:
  server-dev:
    profiles:
      - dev
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'
    command:
      yarn start

  client-dev:
    user: ${CURRENT_UID}
    profiles:
      - dev
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4500:4500'
    volumes:
      - './client:/app'
    environment:
      VITE_SERVER_URL: "http://localhost:4000"
    command:
      bash -c "yarn && yarn dev --host"

  # Prod containers    
  server-prod:
    profiles:
      - prod
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command:
      yarn start
    environment:
      HTTPS: 'true'
      SSL_CRT_FILE: '/etc/letsencrypt/live/mochatto.com/cert.pem'
      SSL_KEY_FILE: '/etc/letsencrypt/live/mochatto.com/privkey.pem'
      SSL_CA_FILE: '/etc/letsencrypt/live/mochatto.com/fullchain.pem'
    ports:
      - '4000:4000'
  client-prod:
    profiles:
      - prod
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://mochatto.com:4000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '443:4500'
    command:
      npx serve -l 4500 -s ./dist --ssl-key /etc/letsencrypt/live/mochatto.com/privkey.pem --ssl-cert /etc/letsencrypt/live/mochatto.com/cert.pem

      
