version: "3.6"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command:
      yarn start
    environment:
      HTTPS: 'true'
      SSL_CRT_FILE: '/etc/letsencrypt/live/mochatto.com/cert.pem'
      SSL_KEY_FILE: '/etc/letsencrypt/live/mochatto.com/privkey.pem'
      SSL_CA_FILE: '/etc/letsencrypt/live/mochatto.com/fullchain.pem'
    ports:
      - '4000:4000'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://mochatto.com:4000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - '443:4500'
    environment:
      REACT_APP_SERVER_URL: 'https://mochatto.com:4000'
    command:
      npx serve -s ./build --ssl-key /etc/letsencrypt/live/mochatto.com/privkey.pem --ssl-cert /etc/letsencrypt/live/mochatto.com/cert.pem

      
