version: "3.8"
services:
  server-dev:
    user: ${CURRENT_UID}
    profiles:
      - dev
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4000:4000'
    environment:
      MODE: dev
    volumes:
      - './server:/app'
    command:
      bash -c "yarn && yarn dev"

  client-dev:
    user: ${CURRENT_UID}
    profiles:
      - dev
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4500:4500'
    volumes:
      - './client:/app'
    environment:
      VITE_SERVER_URL: "http://localhost:4000"
    command:
      bash -c "yarn && yarn dev --host"


  ###############################################
  # Prod containers    
  server-prod:
    profiles:
      - prod
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: prod
    environment:
      MODE: prod
    command:
      yarn start

  client-prod:
    profiles:
      - prod
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://${API_URL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command:
      bash -c "nginx -g daemon off;"

  client-beta:
    profiles:
      - beta
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://${BETA_PREFIX}.dev-api.${APP_URL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command:
      bash -c "nginx -g daemon off;"
      
