version: "3.0"
services:
  server_prod:
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
    ports:
      - '4000:4000'
    environment:
      HTTPS: "true"
      SSL_CRT_FILE: "/selfsigned.crt"
      SSL_KEY_FILE: "/selfsigned.key"
      SSL_CA_FILE: "/chain.pem"
  client_prod:
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - '4500:4500'
    environment:
      HTTPS: "true"
      SSL_CRT_FILE: "/selfsigned.crt"
      SSL_KEY_FILE: "/selfsigned.key"
      SSL_CA_FILE: "/chain.pem"

      
