version: "3.0"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4500:4500'
    volumes:
      - './client:/app'
    environment:
      REACT_APP_SERVER_URL: "http://localhost:4000"

      
