version: "3.6"
services:
  server-dev:
    profiles:
      - dev
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'
    command:
      yarn start

  client-dev:
    profiles:
      - dev
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4500:4500'
    volumes:
      - './client:/app'
    environment:
      VITE_SERVER_URL: "http://localhost:4000"
    command:
      yarn dev --host

  # Prod containers    
  server-prod:
    profiles:
      - prod
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    command:
      yarn start
    environment:
      HTTPS: 'true'
      SSL_CRT_FILE: '/etc/letsencrypt/live/mochatto.com/cert.pem'
      SSL_KEY_FILE: '/etc/letsencrypt/live/mochatto.com/privkey.pem'
      SSL_CA_FILE: '/etc/letsencrypt/live/mochatto.com/fullchain.pem'
    ports:
      - '4000:4000'
  client-prod:
    profiles:
      - prod
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://${API_URL}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
      
