version: "3.0"
services:
  server_prod:
    build:
      context: ./server
      dockerfile: ./Dockerfile.prod
    ports:
      - '4000:4000'
    environment:
      HTTPS: "true"
      SSL_CRT_FILE: "/server.cert"
      SSL_KEY_FILE: "/server.key"
      SSL_CA_FILE: "/chain.pem"
  client_prod:
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - '443:4500'
    environment:
      HTTPS: "true"
      SSL_CRT_FILE: "/server.cert"
      SSL_KEY_FILE: "/server.key"
      SSL_CA_FILE: "/chain.pem"
      REACT_APP_SERVER_URL: 'https://jimanaka.com:4000'

      
