version: '3.8'

services:
  client-prod:
    expose:
      - ${APP_PORT}
    environment:
      VIRTUAL_HOST: ${APP_URL}
      VIRTUAL_PORT: ${APP_PORT}
      LETSENCRYPT_HOST: ${APP_URL}
      LETSENCRYPT_EMAIL: ${EMAIL}

  server-prod:
    expose:
      - ${API_PORT}
    environment:
      VIRTUAL_HOST: ${API_URL}
      VIRTUAL_PORT: ${API_PORT}
      LETSENCRYPT_HOST: ${API_URL}
      LETSENCRYPT_EMAIL: ${EMAIL}

  client-beta:
    expose:
      - ${APP_PORT}
    environment:
      VIRTUAL_HOST: ${BETA_PREFIX}.dev.${APP_URL}
      VIRTUAL_PORT: ${APP_PORT}
      LETSENCRYPT_HOST: ${BETA_PREFIX}.dev.${APP_URL}
      LETSENCRYPT_EMAIL: ${EMAIL}

  server-beta:
    extends:
      file: docker-compose.yaml
      service: server-prod
    expose:
      - ${API_PORT}
    environment:
      VIRTUAL_HOST: ${BETA_PREFIX}.dev-api.${APP_URL}
      VIRTUAL_PORT: ${API_PORT}
      LETSENCRYPT_HOST: ${BETA_PREFIX}.dev-api.${APP_URL}
      LETSENCRYPT_EMAIL: ${EMAIL}


networks:
    default:
        external:
            name: nginx-proxy


