version: "3.8"
services:
  server-dev:
    user: ${CURRENT_UID}
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4000:4000'
    environment:
      MODE: dev
    volumes:
      - './server:/app'
    command:
      bash -c "yarn && yarn dev"

  client-dev:
    user: ${CURRENT_UID}
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: base
    ports:
      - '4500:4500'
    volumes:
      - './client:/app'
    environment:
      VITE_SERVER_URL: "http://localhost:4000"
    command:
      bash -c "yarn && yarn dev --host"

  client-test:
    build:
      context: ./client
      dockerfile: ./Dockerfile.test
      target: test
    command:
      yarn test

  client-test-headed:
    extends:
      service: client-test
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority
    environment:
      QT_XQQ_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    command:
      yarn test-headed

  ###############################################
  # Prod containers    
  server-prod:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: prod
    environment:
      MODE: prod
    command:
      yarn start

  client-prod:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://${API_URL}
    command:
      nginx -g 'daemon off;'

  client-beta:
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: prod
      args:
        serverurl: https://${BETA_PREFIX}.dev-api.${APP_URL}
    command:
      nginx -g 'daemon off;'
      
