version: "3.0"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '4500:4500'
    volumes:
      - './client:/app'

      
