name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: Tell us about the expected behaviour
      value: "Expected Behaviour"
    validations:
      required: true
  - type: textarea
    id: what-actually-happened
    attributes:
      label: Actual Behaviour
      description: What actually happened?
      placeholder: Tell us about what you did and what happened?
      value: "What happened?"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce the problem
      description: How exactly did you make that bug appear? (Videos would be nice too!)
      placeholder: How did the bug occured?
      value: "How did it occur?"
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Any additional info? (Any way to reproduce the bug, which version/commit hash it happened? OS)
      placeholder: Give us any additional info.
      value: "Additional Info?"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
