name: Feature Request
description: Additional Features
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the feature request!
  - type: textarea
    id: request
    attributes:
      label: What feature?
      description: What feature do you think could improve this product?
      placeholder: Tell us what you would like to see!
    validations:
      required: true
