version: "3.8"
services: 
  jenkins-blue-ocean:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      VIRTUAL_HOST: jenkins.${DOMAIN}
      VIRTUAL_PORT: 8080
      LESTSENCRYPT_HOST: jenkins.${DOMAIN}
      LESTSENCRYPT_EMAIL: ${EMAIL}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  jenkins-data:

networks:
  default:
    external:
      name: nginx-proxy

