name: Checks for build
'on': pull_request
jobs:
  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: yarn install --frozen-lockfile 
      - name: Run ESLint
        run: yarn lint
      - name: Run build
        run: yarn build

  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: yarn install --frozen-lockfile 
      - name: Run TSLint
        run: yarn lint
      - name: Run build
        run: yarn build
